version: 2
updates:
  - package-ecosystem: "pnpm"
    directory: "/"
    schedule:
      interval: "daily"
    versioning-strategy: "increase"
    labels:
      - "📦 Dependencies"
      - "🤖 Dependabot"
