import type { PermissionName } from "oceanic.js";

export const permissions: Record<PermissionName, string> = {
  CREATE_INSTANT_INVITE: "Create Instant Invite",
  KICK_MEMBERS: "Kick Members",
  BAN_MEMBERS: "Ban Members",
  ADMINISTRATOR: "Administrator",
  MANAGE_CHANNELS: "Manage Channels",
  MANAGE_GUILD: "Manage Guild",
  ADD_REACTIONS: "Add Reactions",
  VIEW_AUDIT_LOG: "View Audit Log",
  PRIORITY_SPEAKER: "Priority Speaker",
  STREAM: "Stream",
  VIEW_CHANNEL: "View Channel",
  SEND_MESSAGES: "Send Messages",
  SEND_TTS_MESSAGES: "Send TTS Nessages",
  MANAGE_MESSAGES: "Manage Messages",
  EMBED_LINKS: "Embed Links",
  ATTACH_FILES: "Attach Files",
  READ_MESSAGE_HISTORY: "Read Message History",
  MENTION_EVERYONE: "Mention Everyone",
  USE_EXTERNAL_EMOJIS: "Use External Emojis",
  VIEW_GUILD_INSIGHTS: "View Guild Insights",
  CONNECT: "Connect",
  SPEAK: "Speak",
  MUTE_MEMBERS: "Mute Members",
  DEAFEN_MEMBERS: "Deafen Members",
  MOVE_MEMBERS: "Move Members",
  USE_VAD: "Use VAD",
  CHANGE_NICKNAME: "Change Nickname",
  MANAGE_NICKNAMES: "Manage Nicknames",
  MANAGE_ROLES: "Manage Roles",
  MANAGE_WEBHOOKS: "Manage Webhooks",
  MANAGE_GUILD_EXPRESSIONS: "Manage Guild Expressions",
  USE_APPLICATION_COMMANDS: "Use Application Commands",
  REQUEST_TO_SPEAK: "Request To Speak",
  MANAGE_EVENTS: "Manage Events",
  MANAGE_THREADS: "Manage Threads",
  CREATE_PUBLIC_THREADS: "Create Public Threads",
  CREATE_PRIVATE_THREADS: "Create Private Threads",
  USE_EXTERNAL_STICKERS: "Use External Stickers",
  SEND_MESSAGES_IN_THREADS: "Send Messages In Threads",
  USE_EMBEDDED_ACTIVITIES: "Use Embedded Activities",
  MODERATE_MEMBERS: "Timeout Members",
  VIEW_CREATOR_MONETIZATION_ANALYTICS: "View Creator Monetization Analytics",
  USE_SOUNDBOARD: "Use Soundboard",
  CREATE_GUILD_EXPRESSIONS: "Create Guild Expressions",
  CREATE_EVENTS: "Create Events",
  USE_EXTERNAL_SOUNDS: "Use External Sounds",
  SEND_VOICE_MESSAGES: "Send Voice Messages",
  USE_CLYDE_AI: "Use Clyde AI",
  SET_VOICE_CHANNEL_STATUS: "Set Voice Channel Status",
};
