name: Biome

on: [push, pull_request]

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - name: Setup
        uses: biomejs/setup-biome@v2
        with:
          version: latest
      - name: Run
        run: biome ci --formatter-enabled=false --linter-enabled=true --organize-imports-enabled=true .
