name: Prettier

on: [push, pull_request]

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - name: Format
        uses: creyD/prettier_action@v4.3
        with:
          prettier_options: --write **/*.{ts,js,mjs,json,md,mdx}
          commit_message: "Format files with Prettier"
